# LaTeX2HTML 0.6.5 (Tue Nov 15 1994)
# Associate image original text (scrambled) with physical files.

$key = q/{}$itQ_1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43717.gif">'; 
$key = q/{}$its_1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap44145.gif">'; 
$key = q/{}$itT_2${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43487.gif">'; 
$key = q/{}$hboxitinteger+hboxrm0.5${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41707.gif">'; 
$key = q/{}$_k${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40519.gif">'; 
$key = q/{}$itP_2,1ldotsP_2,hboxscriptsizeitn${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43547.gif">'; 
$key = q/{}(pi){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40211.gif">'; 
$key = q/{}(logleft((1+itz)sqrt1-1itz^2right)){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40844.gif">'; 
$key = q/{}$ita_j${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40277.gif">'; 
$key = q/{}$itP_2,hboxscriptsizeiti${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43553.gif">'; 
$key = q/{tabular*}textwidth@l@extracolsepfillll@+++EV(cons'a'b);SPM_amp;***EVNIL;SPM_amp;EV()++EV(hairy-loop);SPM_amp;**EV(A.B);SPM_amp;EV((A.B))+EV(floor134);SPM_amp;*EV3;SPM_amp;EV(31){tabular*}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tabular19313.gif">'; 
$key = q/{}$1011_2${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40197.gif">'; 
$key = q/{tabular*}textwidth@extracolsepfilllll@cdpathname;SPM_amp;cdpathname-device;SPM_amp;cdnamestringcdtruename;SPM_amp;cdpathname-directory;SPM_amp;cdfile-namestringcdparse-namestring;SPM_amp;cdpathname-name;SPM_amp;cddirectory-namestringcdmerge-pathnames;SPM_amp;cdpathname-type;SPM_amp;cdhost-namestringcdpathname-host;SPM_amp;cdpathname-version;SPM_amp;cdenough-namestring{tabular*}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tabular26752.gif">'; 
$key = q/{}(displaystyleitz=lim_hboxscriptsizeityrightarrow-inftyitf(0+ityiti)){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41102.gif">'; 
$key = q/{}$ita_1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap42265.gif">'; 
$key = q/{}$ita_1ldotsita_hboxscriptsizeitn${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43607.gif">'; 
$key = q/{}$2^hboxscriptsizeits${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40315.gif">'; 
$key = q/{}$itP_1,1ldotsP_1,hboxscriptsizeitn${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43545.gif">'; 
$key = q/{}(ite^hboxscriptsizeiticdothboxscriptsizeitradians){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40831.gif">'; 
$key = q/{}$itk;SPM_lt;itj${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40583.gif">'; 
$key = q/{}EV{}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap44281.gif">'; 
$key = q/{}(displaystylearcsinitz=mathoprmarcsinhnolimitsitiitzoveriti){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41089.gif">'; 
$key = q/{}(mathoprmarccoshnolimitsitz=2logleft(sqrt(itz+1)2+sqrt(itz-1)2right)){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41097.gif">'; 
$key = q/{}$0^0=1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41167.gif">'; 
$key = q/{}$itscdotitfcdotitb^hboxscriptsizeite-hboxscriptsizeitp${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40217.gif">'; 
$key = q/{}(itk''){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap44083.gif">'; 
$key = q/{}$itaccessorcopyhyphboxname_1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43691.gif">'; 
$key = q/{}$itb^2-4itaitc${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43137.gif">'; 
$key = q/{}$-1.0${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41723.gif">'; 
$key = q/{}(arccositz=-itilogleft(itz+itisqrt1-itz^2right)){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41090.gif">'; 
$key = q/{displaymath}itR_itC={(itC,itC_1),(itC_1,itC_2),ldots,(itC_hboxscriptsizeitn-1,itC_hboxscriptsizeitn)}{displaymath}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_displaymath43397.gif">'; 
$key = q/{}$_2${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40517.gif">'; 
$key = q/{}$itC_hboxscriptsizeiti${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43425.gif">'; 
$key = q/{}$itdeclaration_hboxscriptsizeitm${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43711.gif">'; 
$key = q/{tabular*}textwidth@l@extracolsepfilllll@elt;SPM_amp;reverse;SPM_amp;map;SPM_amp;removelength;SPM_amp;nreverse;SPM_amp;some;SPM_amp;remove-duplicatessubseq;SPM_amp;concatenate;SPM_amp;every;SPM_amp;deletecopy-seq;SPM_amp;position;SPM_amp;notany;SPM_amp;delete-duplicatesfill;SPM_amp;find;SPM_amp;notevery;SPM_amp;substitutereplace;SPM_amp;sort;SPM_amp;reduce;SPM_amp;nsubstitutecount;SPM_amp;merge;SPM_amp;search;SPM_amp;mismatch{tabular*}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tabular15191.gif">'; 
$key = q/{}$itb^,hboxscriptsizeitp-1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40223.gif">'; 
$key = q/{}$2^hboxscriptsizeits-1-1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40313.gif">'; 
$key = q/{}$itvariablecopyhyphboxname_hboxscriptsizeitn${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43693.gif">'; 
$key = q/{}$itslotcopyhyphboxentry_1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43705.gif">'; 
$key = q/{}(-itilogleft(itz+itisqrt1-itz^2right)){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40834.gif">'; 
$key = q/{}((4+0iti)(+0+iti)=((4)(+0)-(+0)(1))+((4)(1)+(+0)(+0))iti){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41703.gif">'; 
$key = q/{}$_1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40509.gif">'; 
$key = q/{tabular*}linewidth@extracolsepfilllll@cdcompile-file;SPM_amp;cdfile-write-date;SPM_amp;cdpathname-namecdcompile-file-pathname;SPM_amp;cdhost-namestring;SPM_amp;cdpathname-typecddelete-file;SPM_amp;cdload;SPM_amp;cdpathname-versioncddirectory;SPM_amp;cdnamestring;SPM_amp;cdprobe-filecddirectory-namestring;SPM_amp;cdopen;SPM_amp;cdrename-filecddribble;SPM_amp;cdpathname;SPM_amp;cdtranslate-pathnamecded;SPM_amp;cdpathname-device;SPM_amp;cdtruenamecdenough-namestring;SPM_amp;cdpathname-directory;SPM_amp;cdwild-pathname-pcdfile-author;SPM_amp;cdpathname-host;SPM_amp;cdwith-open-filecdfile-namestring;SPM_amp;cdpathname-match-p;SPM_amp;{tabular*}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tabular26566.gif">'; 
$key = q/{}$2^hboxscriptsizeitindex${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41803.gif">'; 
$key = q/{}$C=itP_hboxscriptsizeiti${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43533.gif">'; 
$key = q/{}(itx^32=ite^(32)loghboxscriptsizeitx=ite^(32)pihboxscriptsizeithboxscriptsizeiti=-iti){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40797.gif">'; 
$key = q/{}$105_8${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40193.gif">'; 
$key = q/{}(2^hboxscriptsizeitposition){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41864.gif">'; 
$key = q/{}(-192){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40202.gif">'; 
$key = q/{tabular*}linewidth@extracolsepfillc@cccl@LT;SPM_amp;CT;SPM_amp;EX;SPM_amp;CTTM;SPM_amp;Actionhlinespyes;SPM_amp;yes;SPM_amp;--;SPM_amp;--;SPM_amp;processbodyincompile-time-toomodeyes;SPM_amp;no;SPM_amp;yes;SPM_amp;yes;SPM_amp;processbodyincompile-time-toomodeyes;SPM_amp;no;SPM_amp;--;SPM_amp;no;SPM_amp;processbodyinnot-compile-timemodeyes;SPM_amp;no;SPM_amp;no;SPM_amp;--;SPM_amp;processbodyinnot-compile-timemodeno;SPM_amp;yes;SPM_amp;--;SPM_amp;--;SPM_amp;evaluatebodyno;SPM_amp;no;SPM_amp;yes;SPM_amp;yes;SPM_amp;evaluatebodyno;SPM_amp;no;SPM_amp;--;SPM_amp;no;SPM_amp;donothingno;SPM_amp;no;SPM_amp;no;SPM_amp;--;SPM_amp;donothinghline{tabular*}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tabular3747.gif">'; 
$key = q/{}$[-4.1,4.1]${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41315.gif">'; 
$key = q/{}(logleft(itz+sqrt1+itz^2right)){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40842.gif">'; 
$key = q/{}Xquote{}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap42523.gif">'; 
$key = q/{}$itS'${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43153.gif">'; 
$key = q/{}$itg(itz)=sqrt1-itz^2${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41331.gif">'; 
$key = q/{}$itS_1neqitS_2${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43325.gif">'; 
$key = q/{}$[-pi,pi]${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41131.gif">'; 
$key = q/{}((pi2)-arcsinitz){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40836.gif">'; 
$key = q/{}(-itilogleft(itiitz+sqrt1-itz^2right)){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40833.gif">'; 
$key = q/{}$2^hboxscriptsizeitj${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41801.gif">'; 
$key = q/{}$1.0${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41725.gif">'; 
$key = q/{}((ite^hboxscriptsizeitz+ite^-hboxscriptsizeitz)2){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40840.gif">'; 
$key = q/{}$cositz=itg(sinitz)${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41333.gif">'; 
$key = q/{}$t_1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap44337.gif">'; 
$key = q/{}$(itC,itD)${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43417.gif">'; 
$key = q/{}$itS_hboxscriptsizeitC${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43435.gif">'; 
$key = q/{}$itQ_hboxscriptsizeitn${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43719.gif">'; 
$key = q/{}$[0,itM)${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41893.gif">'; 
$key = q/{}(logitz=left(logleft|itzright|right)+iti(mathoprmphasenolimitsitz)){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41085.gif">'; 
$key = q/{}$itN_hboxscriptsizeiti${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43463.gif">'; 
$key = q/{}$itT_1,ldots,T_hboxscriptsizeitn${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43369.gif">'; 
$key = q/{}$itt_hboxscriptsizeitm${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap44143.gif">'; 
$key = q/{}$itdeclaration_1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43681.gif">'; 
$key = q/{}$itX=itNitM${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41897.gif">'; 
$key = q/{}(-itilogleft((1+itiity)sqrt1(1+ity^2)right)){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40837.gif">'; 
$key = q/{}$langleitM_k;ita_1ldotsita_hboxscriptsizeitnrangle${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43601.gif">'; 
$key = q/{tabular*}textwidth@extracolsepfilllll@cdstreamp;SPM_amp;cdpathname-host;SPM_amp;cdnamestringcdpathname;SPM_amp;cdpathname-device;SPM_amp;cdfile-namestringcdtruename;SPM_amp;cdpathname-directory;SPM_amp;cddirectory-namestringcdmerge-pathnames;SPM_amp;cdpathname-name;SPM_amp;cdhost-namestringcdopen;SPM_amp;cdpathname-type;SPM_amp;cdenough-namestringcdprobe-file;SPM_amp;cdpathname-version;SPM_amp;cddirectory{tabular*}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tabular19686.gif">'; 
$key = q/{}$-2^hboxscriptsizeits-1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40311.gif">'; 
$key = q/{displaymath}itR=bigcup_textstyleitcinitS_hboxscriptsizeitCitR_hboxscriptsizeitc{displaymath}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_displaymath43403.gif">'; 
$key = q/{tabular*}textwidth@l@extracolsepfillll@$sinitiitz=itisinhitz$;SPM_amp;$sinhitiitz=itisinitz$;SPM_amp;$arctanitiitz=itimathoprmarctanhnolimitsitz$$cositiitz=coshitz$;SPM_amp;$coshitiitz=cositz$;SPM_amp;$mathoprmarcsinhnolimitsitiitz=itiarcsinitz$$tanitiitz=ititanhitz$;SPM_amp;$arcsinitiitz=itimathoprmarcsinhnolimitsitz$;SPM_amp;$mathoprmarctanhnolimitsitiitz=itiarctanitz${tabular*}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tabular12443.gif">'; 
$key = q/{}(displaystylemathoprmarctanhnolimitsitz=left(log(1+itz)-log(1-itz)right)over2){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41100.gif">'; 
$key = q/{}((-52)^15){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40209.gif">'; 
$key = q/{}((ite^hboxscriptsizeitz-ite^-hboxscriptsizeitz)2){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40839.gif">'; 
$key = q/{}$itS={cdpie,discretionarycdapple,discretionarycdcinnamon,discretionarycdfruit,discretionarycdspice,discretionarycdfood,discretionarycdstandardcopyQhyphboxdiscretionaryobject,discretionarycdt}${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43489.gif">'; 
$key = q/{}$ita_hboxscriptsizeitn${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40275.gif">'; 
$key = q/{}$lbrack!lbrackdownarrow!hboxitslot-option,rbrack!rbrack${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43659.gif">'; 
$key = q/{}$itC_itn${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43453.gif">'; 
$key = q/{}(2^hboxscriptsizeitposition+hboxscriptsizeitsize-1){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41863.gif">'; 
$key = q/{}(logleft(itz+(itz+1)sqrt(itz-1)(itz+1)right)){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40843.gif">'; 
$key = q/{}$itS_itC${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43401.gif">'; 
$key = q/{}$itC_2,ldots,C_hboxscriptsizeitn-1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43345.gif">'; 
$key = q/{}$10^hboxscriptsizeitk${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap42691.gif">'; 
$key = q/{}$t_2${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap44339.gif">'; 
$key = q/{}$itvariablecopyhyphboxname_1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43689.gif">'; 
$key = q/{}$its_hboxscriptsizeiti${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap44051.gif">'; 
$key = q/{}$itT_1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43475.gif">'; 
$key = q/{}(displaystylelog(1+itiity)-log(1-itiity)over2iti){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40838.gif">'; 
$key = q/{}EQ{}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40269.gif">'; 
$key = q/{}$itslotcopyhyphboxname_hboxscriptsizeitj${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43739.gif">'; 
$key = q/{}$itR={(cdapple,discretionarycdcinnamon),discretionary(cdcinnamon,discretionarycdstandardcopyQhyphboxdiscretionaryobject),discretionary(cdapple,discretionarycdfruit),discretionary(cdfruit,discretionarycdstandardcopyQhyphboxdiscretionaryobject),discretionary(cdcinnamon,discretionarycdspice),discretionary(cdspice,discretionarycdstandardcopyQhyphboxdiscretionaryobject),discretionary(cdfruit,discretionarycdfood),discretionary(cdfood,discretionarycdstandardcopyQhyphboxdiscretionaryobject),discretionary(cdspice,discretionarycdfood),discretionary(cdstandardcopyQhyphboxdiscretionaryobject,discretionarycdt)}${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43503.gif">'; 
$key = q/{}$2^200${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap42679.gif">'; 
$key = q/{}Xcircumflex{}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43053.gif">'; 
$key = q/{}(arcsinitz=-itilogleft(itiitz+sqrt1-itz^2right)){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41088.gif">'; 
$key = q/{}(_hboxscriptsizeitn){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43829.gif">'; 
$key = q/{}$langleitM_1;ita_1ldotsita_hboxscriptsizeitnrangle${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43599.gif">'; 
$key = q/{}$itcinitS_hboxscriptsizeitC${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43407.gif">'; 
$key = q/{}(logleft|itzright|+itimathoprmphasenolimitsitz){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40798.gif">'; 
$key = q/{}$(1+itz)(1-itz)${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41325.gif">'; 
$key = q/{tabular*}textwidth@extracolsepfilllll@cdopen;SPM_amp;cdrename-file~~~~~~~;SPM_amp;cdfile-write-date~~~~~cdwith-open-file~;SPM_amp;cddelete-file;SPM_amp;cdfile-authorcdload;SPM_amp;cdprobe-file;SPM_amp;cddirectorycdcompile-file{tabular*}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tabular26779.gif">'; 
$key = q/{}$itC'${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43921.gif">'; 
$key = q/{}(_hboxscriptsizeitm){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43822.gif">'; 
$key = q/{}${itN_1,ldots,itN_hboxscriptsizeitm}${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43441.gif">'; 
$key = q/{}$^3${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap44664.gif">'; 
$key = q/{}$piiti2${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41255.gif">'; 
$key = q/{}(log_hboxscriptsizeitbitz=(logitz)(logitb)){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41086.gif">'; 
$key = q/{}$itA'${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43163.gif">'; 
$key = q/{}Xarrowright{}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap42605.gif">'; 
$key = q/{}$[0.0,1.0)${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41905.gif">'; 
$key = q/{}$[itA,itB)${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41885.gif">'; 
$key = q/{}$10^7${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap42697.gif">'; 
$key = q/{}$itf(itz)=(itz-1)(itz+1)${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41327.gif">'; 
$key = q/{}(_hboxscriptsizeitj){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap44030.gif">'; 
$key = q/{}$itt_1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43961.gif">'; 
$key = q/{}(displaystyleitz=lim_hboxscriptsizeitxrightarrow+inftyitf(itx+0iti)){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41101.gif">'; 
$key = q/{}$itf(itz)${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41301.gif">'; 
$key = q/{}(arccositz=piover2-arcsinitz){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41091.gif">'; 
$key = q/{}(itx^32=ite^(32)loghboxscriptsizeitx=ite^(32)(2pi3)hboxscriptsizeiti=ite^pihboxscriptsizeiti=-1){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40795.gif">'; 
$key = q/{}$itt_1,ldots,,itt_hboxscriptsizeitm${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap44125.gif">'; 
$key = q/{}(e^pii){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40201.gif">'; 
$key = q/{tabular*}linewidth@l@extracolsepfillllc@multicolumn2cCondition;SPM_amp;CartesianLocus;SPM_amp;RangeofResulthlinesphboxto0.4in$ity=0$hss;SPM_amp;hboxto0.4in$itx;SPM_gt;0$hss;SPM_amp;hboxto1.6inPositiveitx-axishss;SPM_amp;$0$$ity;SPM_gt;0$;SPM_amp;$itx;SPM_gt;0$;SPM_amp;QuadrantI;SPM_amp;$0;SPM_lt;rmresult;SPM_lt;pi2$$ity;SPM_gt;0$;SPM_amp;$itx=0$;SPM_amp;Positiveity-axis;SPM_amp;$pi2$$ity;SPM_gt;0$;SPM_amp;$itx;SPM_lt;0$;SPM_amp;QuadrantII;SPM_amp;$pi2;SPM_lt;rmresult;SPM_lt;pi$$ity=0$;SPM_amp;$itx;SPM_lt;0$;SPM_amp;Negativeitx-axis;SPM_amp;$pi$$ity;SPM_lt;0$;SPM_amp;$itx;SPM_lt;0$;SPM_amp;QuadrantIII;SPM_amp;$-pi;SPM_lt;rmresult;SPM_lt;-pi2$$ity;SPM_lt;0$;SPM_amp;$itx=0$;SPM_amp;Negativeity-axis;SPM_amp;$-pi2$$ity;SPM_lt;0$;SPM_amp;$itx;SPM_gt;0$;SPM_amp;QuadrantIV;SPM_amp;$-pi2;SPM_lt;rmresult;SPM_lt;0$$ity=0$;SPM_amp;$itx=0$;SPM_amp;Origin;SPM_amp;errorhline{tabular*}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tabular12036.gif">'; 
$key = q/{tabular*}linewidth@l@extracolsepfillllc@multicolumn2cCondition;SPM_amp;CartesianLocus;SPM_amp;RangeofResulthlinesphboxto0.4in$ity=+0$hss;SPM_amp;hboxto0.4in$itx;SPM_gt;0$hss;SPM_amp;hboxto1.6inJustabovepositiveitx-axishss;SPM_amp;$+0$$ity;SPM_gt;0$;SPM_amp;$itx;SPM_gt;0$;SPM_amp;QuadrantI;SPM_amp;$+0;SPM_lt;rmresult;SPM_lt;pi2$$ity;SPM_gt;0$;SPM_amp;$itx=pm0$;SPM_amp;Positiveity-axis;SPM_amp;$pi2$$ity;SPM_gt;0$;SPM_amp;$itx;SPM_lt;0$;SPM_amp;QuadrantII;SPM_amp;$pi2;SPM_lt;rmresult;SPM_lt;pi$$ity=+0$;SPM_amp;$itx;SPM_lt;0$;SPM_amp;Justbelownegativeitx-axis;SPM_amp;$pi$$ity=-0$;SPM_amp;$itx;SPM_lt;0$;SPM_amp;Justabovenegativeitx-axis;SPM_amp;$pi$$ity;SPM_lt;0$;SPM_amp;$itx;SPM_lt;0$;SPM_amp;QuadrantIII;SPM_amp;$-pi;SPM_lt;rmresult;SPM_lt;-pi2$$ity;SPM_lt;0$;SPM_amp;$itx=pm0$;SPM_amp;Negativeity-axis;SPM_amp;$-pi2$$ity;SPM_lt;0$;SPM_amp;$itx;SPM_gt;0$;SPM_amp;QuadrantIV;SPM_amp;$-pi2;SPM_lt;rmresult;SPM_lt;-0$$ity=-0$;SPM_amp;$itx;SPM_gt;0$;SPM_amp;Justbelowpositiveitx-axis;SPM_amp;$-0$$ity=+0$;SPM_amp;$itx=+0$;SPM_amp;Nearorigin;SPM_amp;$+0$$ity=-0$;SPM_amp;$itx=+0$;SPM_amp;Nearorigin;SPM_amp;$-0$$ity=+0$;SPM_amp;$itx=-0$;SPM_amp;Nearorigin;SPM_amp;$pi$$ity=-0$;SPM_amp;$itx=-0$;SPM_amp;Nearorigin;SPM_amp;$-pi$hline{tabular*}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tabular12075.gif">'; 
$key = q/{}$itR={(cdcinnamon,discretionarycdstandardcopyQhyphboxdiscretionaryobject),discretionary(cdfruit,discretionarycdstandardcopyQhyphboxdiscretionaryobject),discretionary(cdcinnamon,discretionarycdspice),discretionary(cdspice,discretionarycdstandardcopyQhyphboxdiscretionaryobject),discretionary(cdfruit,discretionarycdfood),discretionary(cdfood,discretionarycdstandardcopyQhyphboxdiscretionaryobject),discretionary(cdspice,discretionarycdfood),discretionary(cdstandardcopyQhyphboxdiscretionaryobject,discretionarycdt)}${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43507.gif">'; 
$key = q/{tabular*}linewidth@l@extracolsepfillll@cdcompile-file;SPM_amp;cded;SPM_amp;cdprobe-filecdcompile-file-pathname;SPM_amp;cdfile-author;SPM_amp;cdrename-filecddelete-file;SPM_amp;cdfile-write-date;SPM_amp;cdtruenamecddirectory;SPM_amp;cdload;SPM_amp;cdwith-open-filecddribble;SPM_amp;cdopen;SPM_amp;{tabular*}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tabular26608.gif">'; 
$key = q/{}((ite^hboxscriptsizeitz-ite^-hboxscriptsizeitz)(ite^hboxscriptsizeitz+ite^-hboxscriptsizeitz)){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40841.gif">'; 
$key = q/{}$itC_hboxscriptsizeiti+1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43347.gif">'; 
$key = q/{}$itC_2${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43591.gif">'; 
$key = q/{}(sqrtitz=ite^(loghboxscriptsizeitz)2){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41083.gif">'; 
$key = q/{}$10^3(hboxscriptsizeitk+1)${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap42681.gif">'; 
$key = q/{}$itt_hboxscriptsizeiti${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43969.gif">'; 
$key = q/{}$itM_i${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43605.gif">'; 
$key = q/{}$^+${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40185.gif">'; 
$key = q/{}$[14,12]${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41287.gif">'; 
$key = q/{}$itform_hboxscriptsizeitk${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43687.gif">'; 
$key = q/{}$itS={cdcinnamon,discretionarycdspice,discretionarycdfood,discretionarycdstandardcopyQhyphboxdiscretionaryobject,discretionarycdt}${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43509.gif">'; 
$key = q/{}$(cdfruit,discretionarycdstandardcopyQhyphboxdiscretionaryobject)${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43495.gif">'; 
$key = q/{}$itC_hboxscriptsizeitn${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43341.gif">'; 
$key = q/{}$^*${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40183.gif">'; 
$key = q/{}(mathoprmarctanhnolimitsitz=logleft((1+itz)sqrt1(1-itz^2)right)){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41099.gif">'; 
$key = q/{}$[34,1]${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41289.gif">'; 
$key = q/{}$langleitM_hboxscriptsizeitiita_1ldotsita_hboxscriptsizeitnrangle${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43609.gif">'; 
$key = q/{}$ita_hboxscriptsizeitj${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40279.gif">'; 
$key = q/{}(sqrtitx^3=sqrt-1=iti){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40796.gif">'; 
$key = q/{tabular*}textwidth@l@extracolsepfilllllll@~~~itargument1~~;SPM_amp;0;SPM_amp;0;SPM_amp;1;SPM_amp;1~~~itargument2~~;SPM_amp;0;SPM_amp;1;SPM_amp;0;SPM_amp;1;SPM_amp;itOperationnamehlinespbit-and;SPM_amp;0;SPM_amp;0;SPM_amp;0;SPM_amp;1;SPM_amp;rmandbit-ior;SPM_amp;0;SPM_amp;1;SPM_amp;1;SPM_amp;1;SPM_amp;rminclusiveorbit-xor;SPM_amp;0;SPM_amp;1;SPM_amp;1;SPM_amp;0;SPM_amp;rmexclusiveorbit-eqv;SPM_amp;1;SPM_amp;0;SPM_amp;0;SPM_amp;1;SPM_amp;rmequivalence(exclusivenor)bit-nand;SPM_amp;1;SPM_amp;1;SPM_amp;1;SPM_amp;0;SPM_amp;rmnot-andbit-nor;SPM_amp;1;SPM_amp;0;SPM_amp;0;SPM_amp;0;SPM_amp;rmnot-orbit-andc1;SPM_amp;0;SPM_amp;1;SPM_amp;0;SPM_amp;0;SPM_amp;rmandcomplementofitargument1withitargument2bit-andc2;SPM_amp;0;SPM_amp;0;SPM_amp;1;SPM_amp;0;SPM_amp;rmanditargument1withcomplementofitargument2bit-orc1;SPM_amp;1;SPM_amp;1;SPM_amp;0;SPM_amp;1;SPM_amp;rmorcomplementofitargument1withitargument2bit-orc2;SPM_amp;1;SPM_amp;0;SPM_amp;1;SPM_amp;1;SPM_amp;rmoritargument1withcomplementofitargument2hline{tabular*}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tabular17863.gif">'; 
$key = q/{}$itS_2${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43323.gif">'; 
$key = q/{}$2^15-1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41919.gif">'; 
$key = q/{}$hboxitslot-entry_hboxscriptsizeitj${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43735.gif">'; 
$key = q/{}$itC_hboxfootnotesizermfrom${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43627.gif">'; 
$key = q/{}(_hboxscriptsizeitk''){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap44082.gif">'; 
$key = q/{}(sqrtitx^3=sqrt1=1){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40794.gif">'; 
$key = q/{}$hboxitQ_hboxscriptsizeitj${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43729.gif">'; 
$key = q/{}$10^6hboxscriptsizeitk${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap42685.gif">'; 
$key = q/{}(10^hboxscriptsizeitn-1leqhboxitarg;SPM_lt;10^hboxscriptsizeitn){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap42673.gif">'; 
$key = q/{}$iti_1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap42299.gif">'; 
$key = q/{}$itS={cdapple,discretionarycdcinnamon,discretionarycdfruit,discretionarycdspice,discretionarycdfood,discretionarycdstandardcopyQhyphboxdiscretionaryobject,discretionarycdt}${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43501.gif">'; 
$key = q/{}(mathoprmarccoshnolimitsitz=logleft(itz+(itz+1)sqrt(itz-1)(itz+1)right)){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41096.gif">'; 
$key = q/{}$(itz-1)(itz+1)${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41323.gif">'; 
$key = q/{}$langleitP_1,ldots,itP_hboxscriptsizeitnrangle${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43519.gif">'; 
$key = q/{}(ite^(loghboxscriptsizeitz)2){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40799.gif">'; 
$key = q/{}$itP_hboxscriptsizeiti${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43523.gif">'; 
$key = q/{}$[1.0,2.0)${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41907.gif">'; 
$key = q/{}$2^hboxscriptsizeitj+1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41295.gif">'; 
$key = q/{}$itXcdot(itB-itA)+itA${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41887.gif">'; 
$key = q/{}(logleft((1+itz)sqrt1(1-itz^2)right)){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40845.gif">'; 
$key = q/{}$itR={(cdspice,discretionarycdstandardcopyQhyphboxdiscretionaryobject),discretionary(cdfood,discretionarycdstandardcopyQhyphboxdiscretionaryobject),discretionary(cdspice,discretionarycdfood),discretionary(cdstandardcopyQhyphboxdiscretionaryobject,discretionarycdt)}${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43515.gif">'; 
$key = q/{}(ldots){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40471.gif">'; 
$key = q/{}$itC_1neqC_2${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43361.gif">'; 
$key = q/{}$90^circ${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41737.gif">'; 
$key = q/{}$itk''${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap44121.gif">'; 
$key = q/{}$itC_1,ldots,C_hboxscriptsizeitn${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43423.gif">'; 
$key = q/{}(_2){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43891.gif">'; 
$key = q/{}(displaystylearctanitz=mathoprmarctanhnolimitsitiitzoveriti){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41094.gif">'; 
$key = q/{tabular*}textwidth@l@extracolsepfillll@string=;SPM_amp;string-equal;SPM_amp;string-trimstring;SPM_lt;;SPM_amp;string-lessp;SPM_amp;string-left-trimstring;SPM_gt;;SPM_amp;string-greaterp;SPM_amp;string-right-trimstring;SPM_lt;=;SPM_amp;string-not-greaterp;SPM_amp;string-upcasestring;SPM_gt;=;SPM_amp;string-not-lessp;SPM_amp;string-downcasestring=;SPM_amp;string-not-equal;SPM_amp;string-capitalize{tabular*}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tabular18382.gif">'; 
$key = q/{}$105_16${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40195.gif">'; 
$key = q/{}$itaccessorcopyhyphboxname_hboxscriptsizeitn${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43695.gif">'; 
$key = q/{}$itP_1,hboxscriptsizeiti${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43551.gif">'; 
$key = q/{}(_1){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43885.gif">'; 
$key = q/{}$itfloor(itintegercdot2^hboxscriptsizeitcount${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41807.gif">'; 
$key = q/{}(itx=mathoprmcisnolimits2piover3=-1over2+sqrt3over2iti){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40793.gif">'; 
$key = q/{}$itform_1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43701.gif">'; 
$key = q/{}$2^hboxscriptsizeitn-1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40207.gif">'; 
$key = q/{}(_0){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap44031.gif">'; 
$key = q/{}$itslotcopyhyphboxentry_hboxscriptsizeitj${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43731.gif">'; 
$key = q/{tabular*}textwidth@extracolsepfillll@cdmake-two-way-stream;SPM_amp;cdmake-string-input-streamcdmake-echo-stream;SPM_amp;cdmake-string-output-streamcdmake-broadcast-stream;SPM_amp;cdwith-input-from-stringcdmake-concatenated-stream;SPM_amp;cdwith-output-to-string{tabular*}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tabular26810.gif">'; 
$key = q/{}$-2^15${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41917.gif">'; 
$key = q/{}$10^60${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap42677.gif">'; 
$key = q/{}$langleitM_hboxscriptsizeiti;ita_1ldotsita_hboxscriptsizeitnrangle${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43603.gif">'; 
$key = q/{}$-piiti2${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41253.gif">'; 
$key = q/{}$pi2${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41251.gif">'; 
$key = q/{}$its_hboxscriptsizeitn${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap44055.gif">'; 
$key = q/{}$itslotcopyhyphboxentry_hboxscriptsizeitn${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43707.gif">'; 
$key = q/{tabular*}textwidth@l@extracolsepfillp17pc@cdXtilde:[XlbraceXtilde;[Xtilde];SPM_amp;Print``cd[''foraxector,and``cdXlbrace''otherwise.cdXtilde:XlbraceXtildeSXtilde:[XarrowrightXtildeSXtilde;Xtilde*Xtilde]Xtilde:XcircumflexXtildeXrbrace;SPM_amp;Givenalistoflists,printthepairs.Eachsublisthasthreeelements:theindex(orthevalueifwe'reprintingaxector);aflagthatistrueforeitheraxectororxet(inwhichcasenoarrowisprinted);andthevalue.NotetheuseofcdXtilde:Xlbracetoiterate,andtheuseofcdXtilde:Xcircumflextoavoidprintingaseparatingspaceafterthefinalpair(oratall,iftherearenopairs).cdXtilde:[Xtilde;Xtilde];SPM_amp;Iftherewerepairsandthereareexceptionsoraninfinitepart,printaseparatingspace.cdXtilde$langle$rmnewline$rangle$;SPM_amp;Donothing.Thismerelyallowstheformatcontrolstringtobebrokenacrosstwolines.cdXtildeXlbraceXtildeSXarrowrightXtildeXcircumflexXtildeXrbrace;SPM_amp;Givenalistofexceptionindices,printthem.NotetheuseofcdXtildeXlbracetoiterate,andtheuseofcdXtildeXcircumflextoavoidprintingaseparatingspaceafterthefinalexception(oratall,iftherearenoexceptions).cdXtilde:[Xtilde;Xtilde];SPM_amp;Iftherewereexceptionsandthereisaninfinitepart,printaseparatingspace.cdXtilde[Xtilde*Xtilde;XarrowrightXtildeSXtilde;XarrowrightXtilde*Xtilde];SPM_amp;UsecdXtilde[tochooseoneofthreecasesforprintingtheinfinitepart.cdXtilde:[XrbraceXtilde;]Xtilde];SPM_amp;Print``cd]''foraxector,and``cdXrbrace''otherwise.{tabular*}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tabular25296.gif">'; 
$key = q/{}$ita_2${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap42275.gif">'; 
$key = q/{}$itA_hboxscriptsizeiti${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43543.gif">'; 
$key = q/{}$0^hboxscriptsizeitx${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41177.gif">'; 
$key = q/{}$[3,pi]${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41293.gif">'; 
$key = q/{}$itC_hboxfootnotesizermto${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43629.gif">'; 
$key = q/{}$[pi2,2]${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41291.gif">'; 
$key = q/{}$itR={(cdcinnamon,discretionarycdstandardcopyQhyphboxdiscretionaryobject),discretionary(cdcinnamon,discretionarycdspice),discretionary(cdspice,discretionarycdstandardcopyQhyphboxdiscretionaryobject),discretionary(cdfood,discretionarycdstandardcopyQhyphboxdiscretionaryobject),discretionary(cdspice,discretionarycdfood),discretionary(cdstandardcopyQhyphboxdiscretionaryobject,discretionarycdt)}${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43511.gif">'; 
$key = q/{}$itM=2^hboxfootnotesizeitf${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41899.gif">'; 
$key = q/{}$itw_hboxscriptsizeitj${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40645.gif">'; 
$key = q/{tabular*}textwidth@l@extracolsepfillll@;SPM_amp;rmDefaultedInitialization;SPM_amp;rmContentsrmForm;SPM_amp;rmArgumentList;SPM_amp;rmofSlothlinespcd(make-instance'r);SPM_amp;cd(a1b2);SPM_amp;cd1cd(make-instance'r'a3);SPM_amp;cd(a3b2);SPM_amp;cd3cd(make-instance'r'b4);SPM_amp;cd(b4a1);SPM_amp;cd4cd(make-instance'r'a1'a2);SPM_amp;cd(a1a2b2);SPM_amp;cd1hline{tabular*}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tabular33178.gif">'; 
$key = q/{}$tanhitz=itf(ite^2hboxscriptsizeitz)${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41329.gif">'; 
$key = q/{}$itvariablecopyhyphboxname_hboxscriptsizeitj${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43737.gif">'; 
$key = q/{}$itS={cdcinnamon,discretionarycdfruit,discretionarycdspice,discretionarycdfood,discretionarycdstandardcopyQhyphboxdiscretionaryobject,discretionarycdt}${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43505.gif">'; 
$key = q/{}$(cdspice,discretionarycdstandardcopyQhyphboxdiscretionaryobject)${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43497.gif">'; 
$key = q/{}$-2^hboxscriptsizeitn${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40205.gif">'; 
$key = q/{}$10^12${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap42683.gif">'; 
$key = q/{}$iti_hboxscriptsizeitn-1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap42307.gif">'; 
$key = q/{}$itP_2,hboxscriptsizeiti=hboxtt(cdeql$hboxitobject_2$)${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43565.gif">'; 
$key = q/{}$itT_hboxscriptsizeitn${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43367.gif">'; 
$key = q/{}(arctanitz=-itilogleft((1+itiitz)sqrt1(1+itz^2)right)){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41092.gif">'; 
$key = q/{}(mathoprmarcsinhnolimitsitz=logleft(itz+sqrt1+itz^2right)){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41095.gif">'; 
$key = q/{}$hboxitobject_2${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43569.gif">'; 
$key = q/{}$itC_hboxscriptsizeitj${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43461.gif">'; 
$key = q/{}$langleitM_hboxscriptsizeitjita_1ldotsita_hboxscriptsizeitnrangle${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43611.gif">'; 
$key = q/{}$itC_1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43387.gif">'; 
$key = q/{}$(iti*itn+itk)${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap44203.gif">'; 
$key = q/{}$sqrt1-itz^2${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41335.gif">'; 
$key = q/{}(=((+0)-(+0))+((4)+(+0))iti=+0+4iti){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41704.gif">'; 
$key = q/{}$-pi2${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41199.gif">'; 
$key = q/{}$itR={(cdpie,discretionarycdapple),discretionary(cdapple,discretionarycdcinnamon),discretionary(cdcinnamon,discretionarycdstandardcopyQhyphboxdiscretionaryobject),discretionary(cdapple,discretionarycdfruit),discretionary(cdfruit,discretionarycdstandardcopyQhyphboxdiscretionaryobject),discretionary(cdcinnamon,discretionarycdspice),discretionary(cdspice,discretionarycdstandardcopyQhyphboxdiscretionaryobject),discretionary(cdfruit,discretionarycdfood),discretionary(cdfood,discretionarycdstandardcopyQhyphboxdiscretionaryobject),discretionary(cdspice,discretionarycdfood),discretionary(cdstandardcopyQhyphboxdiscretionaryobject,discretionarycdt)}${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43491.gif">'; 
$key = q/{}(mathoprmarctanhnolimitsitz=logleft((1+itz)sqrt1-1itz^2right)){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41098.gif">'; 
$key = q/{}$10^-3${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap42653.gif">'; 
$key = q/{}(_(hboxscriptsizeitj-1)){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43947.gif">'; 
$key = q/{}$ittx_m${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43965.gif">'; 
$key = q/{}$langleitA_1,ldots,itA_hboxscriptsizeitnrangle${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43517.gif">'; 
$key = q/{}Xarrowdown{}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap42833.gif">'; 
$key = q/{}$itb^hboxscriptsizeitx=0${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41173.gif">'; 
$key = q/{}$itC_hboxfootnotesizeitto${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43635.gif">'; 
$key = q/{}$itS={cdspice,discretionarycdfood,discretionarycdstandardcopyQhyphboxdiscretionaryobject,discretionarycdt}${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43513.gif">'; 
$key = q/{}(itb^hboxscriptsizeitx=ite^hboxscriptsizeitxloghboxscriptsizeitb){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41087.gif">'; 
$key = q/{}$itDinitS_hboxscriptsizeitC${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43419.gif">'; 
$key = q/{}$_hboxscriptsizeitj${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap42353.gif">'; 
$key = q/{}$itS_1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43319.gif">'; 
$key = q/{}$itB'${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43165.gif">'; 
$key = q/{}$;equiv;${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40411.gif">'; 
$key = q/{tabular*}textwidth@l@extracolsepfillll@rmAccessFunction;SPM_amp;rmUpdateFunction;SPM_amp;rmUpdateUsingcdsetfhlinespcdx;SPM_amp;cd(setqxdatum);SPM_amp;cd(setfxdatum)cd(carx);SPM_amp;cd(rplacaxdatum);SPM_amp;cd(setf(carx)datum)cd(symbol-valuex);SPM_amp;cd(setxdatum);SPM_amp;cd(setf(symbol-valuex)datum)hline{tabular*}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tabular5167.gif">'; 
$key = q/{}$hboxitobject_1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43567.gif">'; 
$key = q/{}$10^18${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap42687.gif">'; 
$key = q/{}$lfloor1+(itl-itm)itnrfloor${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap44201.gif">'; 
$key = q/{}(displaystyle2logleft(sqrt1+itzover2+itisqrt1-itzover2right)overi){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40835.gif">'; 
$key = q/{}$itk'${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap44119.gif">'; 
$key = q/{}$itR_hboxscriptsizeitc${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43499.gif">'; 
$key = q/{}$(-pi,pi]${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41127.gif">'; 
$key = q/{}$iti_0${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap42303.gif">'; 
$key = q/{}(itk'){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap44081.gif">'; 
$key = q/{}$2^hboxscriptsizeits-1${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40317.gif">'; 
$key = q/{}$itC_hboxfootnotesizeitfrom${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43651.gif">'; 
$key = q/{}(mathoprmphasenolimitsitz=arctan(Imitz,Reitz)){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41084.gif">'; 
$key = q/{}$itP_1,hboxscriptsizeiti=hboxtt(cdeql$hboxitobject_1$)${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43563.gif">'; 
$key = q/{}$itC_1,ldots,itC_hboxscriptsizeitn${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43399.gif">'; 
$key = q/{}$sqrt1+itz^2${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41321.gif">'; 
$key = q/{}(displaystylearctanitz=log(1+itiitz)-log(1-itiitz)over2iti){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41093.gif">'; 
$key = q/{}$(cdcinnamon,discretionarycdstandardcopyQhyphboxdiscretionaryobject)${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43493.gif">'; 
$key = q/{}(log_102){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40212.gif">'; 
$key = q/{}$itM_1,ldots,itM_hboxscriptsizeitk${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43597.gif">'; 
$key = q/{}$itplog_2itb${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40227.gif">'; 
$key = q/{}EX{}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40159.gif">'; 
$key = q/{}$(itC_1ldotsitC_hboxscriptsizeitn)${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap43447.gif">'; 
$key = q/{}$itw_1,ldots,itw_hboxscriptsizeitn${}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap40641.gif">'; 
$key = q/{}(itceiling(log_2(bfif;itinteger;SPM_lt;0;bfthen;-itinteger;bfelse;itinteger+1))){}/;
$cached_env_img{$key} ='<IMG ALIGN=BOTTOM ALT="" SRC="_24769_tex2html_wrap41797.gif">'; 

1;

